### ISSUE TITLE
use from CLI?

### ISSUE THREAD

**Issue by srl295** [not-dalia/gfm-toc#1]
Hi 👋  @miloush sent me here. Thanks for this tool!  I'm working on https://unicode-org.atlassian.net/browse/CLDR-15105 …

Would you be open to a PR to refactor this so I can run it from a Node.js CLI? (Ideally after a license is attached).  Thanks!

**Comment by not-dalia** [comment]
Hello! Sure, no problem. License is now attached.

**Comment by srl295** [comment]
@not-dalia  example use https://github.com/unicode-org/cldr/pull/1835/files?short_path=8ae27b7#diff-c4b6c89b937f2ebf58963a979403999feddedd3399b7ac47a9db72b35a69f9fe

**Comment by srl295** [comment]
FYI merged. https://github.com/unicode-org/cldr/pull/1835
